// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAebSz-6y1DTI7A-CeI6uZ22OkVzx0SONI',
    appId: '1:371034901502:web:fcb2f168ea0cfa35630eaf',
    messagingSenderId: '371034901502',
    projectId: 'rentadat',
    authDomain: 'rentadat.firebaseapp.com',
    storageBucket: 'rentadat.firebasestorage.app',
    measurementId: 'G-TWW5RS1828',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYuwlyDmXt4_cIzpPE0xJ8UMSnNsTLyHk',
    appId: '1:371034901502:android:f4d95d9e2f0741fd630eaf',
    messagingSenderId: '371034901502',
    projectId: 'rentadat',
    storageBucket: 'rentadat.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBU2jz6xNpGDbGTD6y_hKgsmDStoysrdy8',
    appId: '1:371034901502:ios:a1d7dcd85ed8f331630eaf',
    messagingSenderId: '371034901502',
    projectId: 'rentadat',
    storageBucket: 'rentadat.firebasestorage.app',
    iosBundleId: 'com.example.rental',
  );
}
